name: fund_test_flutter
description: Funding DApp

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
#  flutter_web: any
#  flutter_web_ui: any
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  pedantic: ^1.7.0

flutter:
  uses-material-design: true

