name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@c7282f8b6d4728a9d2a04936f80b38eeda6d91fa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
