name: CI
on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: make server
      run: make -C srv-shared
