name: CI
on: [push]

jobs:


  build-mac:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v1
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3

    - name: make macOS client
      run: make -j3 -C cli-shared
    - uses: actions/upload-artifact@v1
      with:
        name: orchid-mac
        path: cli-shared/out-mac/x86_64/orchid

    - name: make macOS server
      run: make -j3 -C srv-shared
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-mac
        path: srv-shared/out-mac/x86_64/orchidd


  build-app:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v1
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3

    - name: pod install
      run: make -C app-macos out-mac/XCBuildData/build.db
    - name: make macOS .app
      run: debug=ldid make -j3 -C app-macos


  build-ios:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v1
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3

    - name: make iOS .ipa
      run: debug=ldid make -j3 -C app-ios


  build-lnx:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3

    - name: make Linux client
      run: debug=crossndk make -j3 -C cli-shared
    - uses: actions/upload-artifact@v1
      with:
        name: orchid-lnx
        path: cli-shared/out-lnx/x86_64/orchid

    - name: make Linux server
      run: debug=crossndk make -j3 -C srv-shared
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-lnx
        path: srv-shared/out-lnx/x86_64/orchidd


  build-win:
    runs-on: ubuntu-latest

    steps:

    - name: apt-get install
      run: DEBIAN_FRONTEND=noninteractive sudo -E apt-get -y install mingw-w64

    - uses: actions/checkout@v1
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3

    - name: make Windows test
      run: make -j3 -C tst-network target=win

    - name: make Windows server
      run: make -j3 -C srv-shared target=win
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-w64
        path: srv-shared/out-win/x86_64/orchidd.exe


  build-and:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3

    - name: make Android .apk
      run: make -j3 -C app-android
    - uses: actions/upload-artifact@v1
      with:
        name: orchid-apk
        path: app-android/out-and/Orchid.apk
        #path: app-android/build/outputs/apk/release/app-android-release-unsigned.apk
