name: CI
on: [push]

jobs:

  build-mac:
    runs-on: macos-latest

    steps:
    - name: git config
      run: |
        git config --global url."git://git.savannah.gnu.org/".insteadOf "https://git.savannah.gnu.org/git/"
        git config --global url."git://git.savannah.nongnu.org/".insteadOf "https://git.savannah.nongnu.org/git/"
    - uses: actions/checkout@v1
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3
    - name: brew install
      run: brew install meson autoconf automake libtool
    - name: brew link
      run: brew link --force gettext
    - name: pip install
      run: pip install pyyaml
    - name: make macOS client
      run: make -j3 -C cli-shared
    - name: make macOS server
      run: make -j3 -C srv-shared
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-mac
        path: srv-shared/out-mac/x86_64/orchidd

  build-lnx:
    runs-on: ubuntu-latest

    steps:
    - name: git config
      run: |
        git config --global url."git://git.savannah.gnu.org/".insteadOf "https://git.savannah.gnu.org/git/"
        git config --global url."git://git.savannah.nongnu.org/".insteadOf "https://git.savannah.nongnu.org/git/"
    - uses: actions/checkout@v1
    - name: git submodule
      run: git submodule update --init --recursive --jobs 3
    - name: make Linux server
      run: make -j3 -C srv-shared debug=crossndk
    - uses: actions/upload-artifact@v1
      with:
        name: orchidd-lnx
        path: srv-shared/out-lnx/x86_64/orchidd
